#!/usr/bin/env python
#
# Mainly from here:
#   https://developers.google.com/closure/compiler/docs/api-tutorial1
#
# jcc
# Compile a JavaScript program with the google closure compiler, by connecting
# to their api.
#

import httplib, urllib, sys

# Define the parameters for the POST request and encode them in
# a URL-safe format.

if len(sys.argv) <= 1 or sys.argv[1] == '-h':
  print "usage: jcc program.js"
  sys.exit(1)

with open(sys.argv[1], 'r') as f:
  code = f.read()

params = urllib.urlencode([
    ('js_code', code),
    ('compilation_level', 'SIMPLE_OPTIMIZATIONS'),
    ('output_format', 'text'),
    ('output_info', 'compiled_code'),
  ])

# Always use the following value for the Content-type header.
headers = { "Content-type": "application/x-www-form-urlencoded" }
conn = httplib.HTTPConnection('closure-compiler.appspot.com')
conn.request('POST', '/compile', params, headers)
response = conn.getresponse()
data = response.read()
print data
conn.close()
